### ISSUE TITLE
Providers Not Updating

### ISSUE THREAD

**Issue by mytestingsolution** [ssricardo/anki-web-browser#12]
Absolutely amazing add on. I don't know why this isn't basic functionality in Anki.

I've tried updating my providers list, but when I go to use the add on and right click, the default providers are shown.

I'm using Version 2.1.35 (84dcaa86)

And here is my code:

Thank you for any help you can provide!

{
    "browserAlwaysOnTop": true,
    "filteredWords": [],
    "initialBrowserSize": "1200x800",
    "keepBrowserOpened": true,
    "menuShortcut": "Ctrl+Shift+B",
    "providers": [
        {
            "name": "Google Web",
            "url": "https://google.com/search?q={}"
        },
        {
            "name": "En Google Images",
            "url": "https://www.google.com/search?tbm=isch&q={}"
        },
        {
            "name": "Fr Google Images",
            "url": "https://www.google.fr/search?tbm=isch&q={}"
        },
        {
            "name": "Wiktionary",
            "url": "https://en.wiktionary.org/wiki/={}/"
        }
    ],
    "repeatShortcut": "F10",
    "useSystemBrowser": true
}

**Comment by ssricardo** [comment]
I found some issue with config on previous versions.
That was fixed on current version (7.0).
