### ISSUE TITLE
[Suggestion] copying images

### ISSUE THREAD

**Issue by MedBooster** [ssricardo/anki-web-browser#24]
Is it just me, or is it not possible to copy images in you add-on? :) 
![image](https://user-images.githubusercontent.com/95221545/204659296-9bf79892-9c31-4944-87ca-705d5b417cc3.png)

**Comment by ssricardo** [comment]
Hi!

How are you trying to do it? 

You can import images by either:
- Drag & drop into the desired field; or
- Use the right-click menu and "Assign to [field]"

But it's restricted to when you are editing a card. (In review mode - like in the picture - this is not allowed)

**Comment by ssricardo** [comment]
Closing, as the reason was already explained before
