### ISSUE TITLE
23.10Qt6 Broken

### ISSUE THREAD

**Issue by DoctorToBeIn23** [ssricardo/anki-web-browser#28]
On 23.10Qt6 cannot get the add-on to show up in the "Tools."

**Comment by DoctorToBeIn23** [comment]
Not automatically showing up

**Comment by orangelover12** [comment]
I'm suffering from the same problem. :') I would be very grateful if it could be updated for 23.10 QT6

**Comment by ssricardo** [comment]
Hey guys! 
Any specific OS? MacOs/Windows/Linux?
I'll try to have a look on it, but I have to say that I'm quite busy in this end of year, so not sure when I'll have it, ok?!

**Comment by orangelover12** [comment]
I use Windows 11. I would appreciate it if you could take a look when you have free time. Have a wonderful day, ssricardo! 👍

**Comment by DoctorToBeIn23** [comment]
Im on Mac Os

**Comment by honis56** [comment]
> On 23.10Qt6 cannot get the add-on to show up in the "Tools."

same problem

**Comment by ssricardo** [comment]
A new version was just released.
Please check it out

**Comment by DoctorToBeIn23** [comment]
Great working now!
