### ISSUE TITLE
How to concatenate ??

### ISSUE THREAD

**Issue by Almost-Infinite** [ssricardo/anki-web-browser#3]
example: https://google.com/search?q={} + word
it's possible?

**Comment by Almost-Infinite** [comment]
after a few attempts i managed to figure out how to do it, and just put % 20. 
but I'm not able to put the word in quotes e.g: https://google.com/search?q={}%20"word"

**Comment by ssricardo** [comment]
You can try the double quotes with:

> %E2%80%A6

**Comment by Almost-Infinite** [comment]
thanks for the answer, but this code puts ...
I searched and the correct code and %22 
then it would look like this:  https://google.com/search?q={}%20%22word%22
