### ISSUE TITLE
invalid url problem

### ISSUE THREAD

**Issue by drsnn** [ssricardo/anki-web-browser#5]
Hi Ricardo thank you for your awesome extension. i. have a problem when i add a website "https://lexin.nada.kth.se/lexin/#searchinfo=both,swe_tur,ord;" . it says it is a invalid url how can i add this website. Thank you very much. 

eror:
Some URL is invalid.Check the URL and if it contains {} that will be replaced by the text: https://lexin.nada.kth.se/lexin/#searchinfo=both,swe_tur,ord;

thanks

**Comment by ssricardo** [comment]
Hi @drsnn .

I think the accepted character for URL are not considering the comma ",". 

I will create a new version fixing that, but it might take some time.
Before that, you can  make a quick change on the file `config.py`:

replace:

    _validURL = re.compile('^((http|ftp){1}s{0,1}://)([\w._/?&=%#@]|-)+{}([\w._/?&=%#+]|-)*$')

with:

    _validURL = re.compile('^((http|ftp){1}s{0,1}://)([\w._/?&=%#,@]|-)+{}([\w._/?&=%#,+]|-)*$')

> Obs: I haven't tested it - only suggesting but I'm not completely sure
