### ISSUE TITLE
a feature request

### ISSUE THREAD

**Issue by med015** [ssricardo/anki-web-browser#6]
Hi:

Can you tell me please how can I add Reverso Context (German-Arabic) and Reverso Conjugator (German)?

Thank you for this app.

**Comment by ssricardo** [comment]
Hi @med015 !

What's the URL of the website?

**Comment by med015** [comment]
Here they are:
(Enlish-German): https://context.reverso.net/translation/english-german/speaking
(German Verb Conjugator): https://conjugator.reverso.net/conjugation-german-verb-sprechen.html

**Comment by ssricardo** [comment]
Ok.

Go to the configuration and add new providers. The address there will be the following:

(Enlish-German): https://context.reverso.net/translation/english-german/{}
(German Verb Conjugator): https://conjugator.reverso.net/conjugation-german-verb-{}.html

Then later, during the edition or review, you need to select which word to query. 
The way it works is, it only replaces the {} part in the URL with the selected word.

**Comment by med015** [comment]
It works, but It won't take effect until you change the configuration in the config.json file. Here where it got me. thanks bro. @ssricardo
