### ISSUE TITLE
Problem with dict.cc: How to change language via configurations?

### ISSUE THREAD

**Issue by honis56** [ssricardo/anki-web-browser#7]
Hi,
thanks for this useful addon!

I want to change the target language for dict.cc from default English-German to German-Spanish. For this purpose I changed the URL of dict.cc

Tools -> Add-ons -> Web Browser -> Config -> 

            "name": "Dict.cc",
            "url": "https://dees.dict.cc/?s={}"

-> OK -> restart Anki

but if I use the add-on Webbrowser with Dict.cc, the English target language is still displayed instead of the expected Spanish. I am afraid the change of the url in Config is not transported into the program.

How to do it correctly?

Best regards

**Comment by honis56** [comment]
Problem solved. Use Tools -> Anke-Web-Browser config. Sorry, my mistake.

**Comment by ssricardo** [comment]
Ah, great then :100:
